name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionToBump:
        description: 'The version to bump. Major for incompatible API changes, minor for adding BC features'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create tag and release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go get .
      - run: go build -v ./...
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn add -D -E zx@8.1.4 semver@7.6.3
      - name: Run release script
        run: yarn zx ./release.mjs -v $VERSION_TO_BUMP
        env:
          VERSION_TO_BUMP: ${{ inputs.versionToBump }}
          GH_TOKEN: ${{ github.token }}

  notify-slack-failure:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: failure()
    steps:
      - uses: seatsio/seatsio-github-actions/slack-notify-clientlib-release-failure@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
