name: "Release"

on:
  workflow_dispatch:
    branches:
      - main
      - release_automation_test
    inputs:
      tag-and-release-name:
        description: Used for the tag name and release name

jobs:
  run-build:
    uses: seatsio/seatsio-go/.github/workflows/build.yml

  create-tag-and-release:
    name: Create tag and release
    runs-on: ubuntu-latest
    needs:
      -  run-build
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag-and-release-name }}
          release_name: ${{ github.event.inputs.tag-and-release-name }}
          draft: false
          prerelease: false