name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionToBump:
        description: 'The version to bump. Major for incompatible API changes, minor for adding BC features'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create tag and release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go get .
      - run: go build -v ./...
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: install-zx
        run: npm i -g zx
      - id: install-semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
      - run: zx ./release.mjs -v $VERSION_TO_BUMP
        env:
          VERSION_TO_BUMP: ${{ inputs.versionToBump }}
          GH_TOKEN: ${{ github.token }}

  notify-slack-failure:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: failure()
    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          status: FAILED
          channel: build_status
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
